
GET localhost:8080/cidades
Accept: application/json


### Cadastrar cidade
POST localhost:8080/cidades
Accept: application/json
Content-Type: application/json

{
  "nome": "Fortaleza teste",
  "estado": {
    "id": 3,
    "nome": "Ceará"
  }
}

###
PUT localhost:8080/cidades/1
Accept: application/json
Content-Type: application/json

{
  "nome": "Fortaleza teste",
  "estado": {
    "id": 1,
    "nome": "Ceará"
  }
}

###
DELETE localhost:8080/cidades/1
Accept: application/json
Content-Type: application/json
