### Consultar cozinhas
GET localhost:8080/cozinhas
Accept: application/json


### Consultar por id
GET localhost:8080/cozinhas/1
Accept: application/json

### Cadastrar cozinha
POST localhost:8080/cozinhas
Accept: application/json
Content-Type: application/json

{
  "nome": "mega Food4"
}

### atualizar cozinha
PUT localhost:8080/cozinhas/11
Accept: application/json
Content-Type: application/json

{
  "nome": "mega Food2"
}

### remover cozinha
DELETE localhost:8080/cozinhas/1
Accept: application/json
Content-Type: application/json
