###
GET localhost:8080/estados
Accept: application/json


###
POST localhost:8080/estados
Accept: application/json
Content-Type: application/json

{
  "nome": "flores de brasilia "
}

###
PUT localhost:8080/estados/5
Accept: application/json
Content-Type: application/json

{
  "id": 4,
  "nome": "flores "
}

###
DELETE localhost:8080/estados/4
Accept: application/json
Content-Type: application/json
