### Consultar Restaurantes
GET localhost:8080/restaurantes
Accept: application/json

### Consultar Restaurantes por taxa
GET localhost:8080/restaurantes/taxa?taxaInicial=15&taxaFinal=20
Accept: application/json


### Consultar por id
GET localhost:8080/restaurantes/1
Accept: application/json

### Cadastrar Restaurantes
POST localhost:8080/restaurantes
Accept: application/json
Content-Type: application/json

{
  "nome": "",
  "taxaFrete": -12,
  "cozinha": {
    "id": 1
  }
}

### atualizar Restaurantes
PUT localhost:8080/restaurantes/1
Accept: application/json
Content-Type: application/json

{
  "id": "4",
  "nome": "comida jakson",
  "taxaFrete": 14,
  "cozinha": {
    "id": 2,
    "nome": "nber"
  }
}

### remover Restaurantes
DELETE localhost:8080/restaurantes/1
Accept: application/json
Content-Type: application/json


### atualizar parcial
PATCH localhost:8080/restaurantes/2
Accept: application/json
Content-Type: application/json

{
  "nome": "comida jakson",
  "taxaFrete": 45
}

### Consultar Restaurantes  com ferte gratis
GET localhost:8080/restaurantes/teste?nome=a
Accept: application/json

### Consultar Restaurantes  com ferte gratis
DELETE localhost:8080/restaurantes/1/ativo
Accept: application/json